name: release
on:
  workflow_dispatch
jobs:
  docker:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package_target:
          - noble-amd64
      fail-fast: false
    steps:
      - name: configure docker
        run:  |
          echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: checkout packaging
        uses: actions/checkout@v2
        with:
          path: packaging
      - name: checkout wkhtmltopdf with submodules
        uses: actions/checkout@v2
        with:
          repository: wkhtmltopdf/wkhtmltopdf
          path: wkhtmltopdf
          submodules: true
          ref: 0.12.6.x
      - name: build
        run: cd packaging && python3 ./build package-docker --clean ${{ matrix.package_target }} ../wkhtmltopdf
      - uses: softprops/action-gh-release@v2
        with:
          name: wkhtmltopdf 0.12.6.1
          tag: v0.12.6.1
          files: "packaging/targets/*"
          fail_on_unmatched_files: false
          draft: true
          body: Builds of wkhtmltopdf (0.12.6.x branch) for debian and ubuntu (amd64). [build run](${{github.event.repository.html_url}}/actions/runs/${{github.run_id}})